apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: che-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: che
  namespace: ethan
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
