apiVersion: v1
kind: Service
metadata:
  labels:
    app: che
  name: che-host
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: che
<<<<<<< HEAD
  type:
    ClusterIP
=======
#  type:
#    NodePort
>>>>>>> 549a22e1d72dea4a34434f9a8855370ba60f3178
