apiVersion: v1
data:
  CHE_API: http://a55ecb0a5ab5f11e895a102fb6b9cd9d-1275764020.ap-south-1.elb.amazonaws.com/api
  CHE_DEBUG_SERVER: "true"
  CHE_HOST: a55ecb0a5ab5f11e895a102fb6b9cd9d-1275764020.ap-south-1.elb.amazonaws.com
  CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: http://CHE-HOST:8080/agent-binaries/linux_amd64/bootstrapper/bootstrapper
  CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"nginx.ingress.kubernetes.io/rewrite-target":
    "/","nginx.ingress.kubernetes.io/ssl-redirect": "false","nginx.ingress.kubernetes.io/proxy-connect-timeout":
    "3600","nginx.ingress.kubernetes.io/proxy-read-timeout": "3600"}'
  CHE_INFRA_KUBERNETES_INGRESS_DOMAIN: a55ecb0a5ab5f11e895a102fb6b9cd9d-1275764020.ap-south-1.elb.amazonaws.com
  CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN: "5"
  CHE_INFRA_KUBERNETES_MASTER__URL: https://api.aind.devops
  CHE_INFRA_KUBERNETES_NAMESPACE: ethan
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP: "0"
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER: "0"
  CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS: "false"
  CHE_INFRA_KUBERNETES_PVC_STRATEGY: unique
  CHE_INFRA_KUBERNETES_SERVER__STRATEGY: single-host
  CHE_INFRA_KUBERNETES_TRUST__CERTS: "false"
  CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "-1"
  CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS: "-1"
  CHE_INFRASTRUCTURE_ACTIVE: kubernetes
  CHE_JDBC_DATABASE: dbche
  CHE_JDBC_DRIVER__CLASS__NAME: org.postgresql.Driver
  CHE_JDBC_MAX__IDLE: "10"
  CHE_JDBC_MAX__TOTAL: "20"
  CHE_JDBC_MAX__WAIT__MILLIS: "-1"
  CHE_JDBC_PASSWORD: pgchepassword
  CHE_JDBC_URL: jdbc:postgresql://postgres-che:5432/dbche
  CHE_JDBC_USERNAME: pgche
  CHE_KEYCLOAK_AUTH__SERVER__URL: http://a55ecb0a5ab5f11e895a102fb6b9cd9d-1275764020.ap-south-1.elb.amazonaws.com/auth
  CHE_KEYCLOAK_CLIENT__ID: che-public
  CHE_KEYCLOAK_LOGOUT_ENDPOINT: http://a55ecb0a5ab5f11e895a102fb6b9cd9d-1275764020.ap-south-1.elb.amazonaws.com/auth/realms/che/protocol/openid-connect/logout
  CHE_KEYCLOAK_PASSWORD_ENDPOINT: http://a55ecb0a5ab5f11e895a102fb6b9cd9d-1275764020.ap-south-1.elb.amazonaws.com/auth/realms/che/account/password
  CHE_KEYCLOAK_PROFILE_ENDPOINT: http://a55ecb0a5ab5f11e895a102fb6b9cd9d-1275764020.ap-south-1.elb.amazonaws.com/auth/realms/che/account
  CHE_KEYCLOAK_REALM: che
  CHE_KEYCLOAK_TOKEN_ENDPOINT: http://a55ecb0a5ab5f11e895a102fb6b9cd9d-1275764020.ap-south-1.elb.amazonaws.com/auth/realms/che/protocol/openid-connect/token
  CHE_LOCAL_CONF_DIR: /etc/conf
  CHE_LOG_LEVEL: INFO
  CHE_LOGS_APPENDERS_IMPL: plaintext
  CHE_LOGS_DIR: /data/logs
  CHE_MULTIUSER: "true"
  CHE_OAUTH_GITHUB_CLIENTID: ""
  CHE_OAUTH_GITHUB_CLIENTSECRET: ""
  CHE_PORT: "8080"
  CHE_PREDEFINED_STACKS_RELOAD__ON__START: "false"
  CHE_WEBSOCKET_ENDPOINT: ws://a55ecb0a5ab5f11e895a102fb6b9cd9d-1275764020.ap-south-1.elb.amazonaws.com/api/websocket
  CHE_WORKSPACE_AUTO_START: "false"
  CHE_WORKSPACE_FEATURE_API: http://marketplace:80
  JAVA_OPTS: '-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
    -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms20m '
kind: ConfigMap
metadata:
  creationTimestamp: 2018-08-30T04:32:24Z
  labels:
    app: che
  name: che
  namespace: ethan
  resourceVersion: "3519666"
  selfLink: /api/v1/namespaces/ethan/configmaps/che
  uid: b1a77dfc-ac0d-11e8-b348-02fb6b9cd9dc
